Add default support for permit2
0xPolygon/pol-token pull request #27
Opened 2023-09-17 21:22 UTC by gretzke

2023-09-17 22:24 UTC, maxsam4 requested changes

2023-09-17 22:24 UTC, maxsam4 commented on src/PolygonEcosystemToken.sol
> +        _grantRole(PERMIT2_REVOKER_ROLE, governance);
This needs to be different than cap manager bcz cap manager is time locked, this isnt.

2023-09-17 22:24 UTC, maxsam4 commented on src/PolygonEcosystemToken.sol
> +    function revokePermit2Allowance() external onlyRole(PERMIT2_REVOKER_ROLE) {
Add a function to re-enable

2023-09-18 07:49 UTC, DhairyaSethi approved these changes

2023-09-18 08:13 UTC, dev1644 approved these changes

2023-09-18 08:19 UTC, maxsam4 approved these changes

2023-09-18 08:20 UTC, merged

2023-09-18 12:52 UTC, oneski commented
👀